// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tivicgrhwoidjvmqgfxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdmljZ3Jod29pZGp2bXFnZnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxOTc0OTQsImV4cCI6MjA1NDc3MzQ5NH0.m2oJtKvgL8eTkXMp8oZsxMKglz60FGDIQBx_aYzP6vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);